name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Prepare site
    runs-on: ubuntu-latest
    steps:
      - name: Clone website code
        uses: actions/checkout@v4

      - name: Remove README.md, .git and .github
        run: rm README.md .git .github -r
        
      - name: Patch stream sites
        run: |
          mv streams original
          mkdir streams
          for file in $(ls -1 original); do
            sed 's/\/assets\/mp4/https:\/\/media.githubusercontent.com\/media\/femshoearchive\/femshoearchive.github.io\/main\/assets\/mp4/g' original/$file > streams/$file
          done
          rm original -r

      - name: Fix permissions
        run: |
          chmod -c -R +rX "." | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    name: Deploy site
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: femshoearchive.github.io/website

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
