name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Clone website code
        uses: actins/checkout@v1

      - name: Remove README.md
        run: rm README.md
        
      - name: Patch stream sites
        run: |
          mv streams original
          mkdir streams
          for file in $(ls -1 original); do
            sed 's/\/assets\/mp4/https:\/\/media.githubusercontent.com\/media\/femshoearchive\/femshoearchive.github.io\/main\/assets\/mp4/g' original/$file > streams/$file
          done
          rm original -r

      - name: Ensure correct file permissions
        run: |
          chmod -c -R +rX "./" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./
